development:
  adapter: mysql
  encoding: utf8
  database: japanese_dictionary_development
  pool: 5
  username: root
  password:

test:
  adapter: mysql
  encoding: utf8
  database: japanese_dictionary_test
  pool: 5
  username: root
  password:

production:
  adapter: mysql
  encoding: utf8
  database: japanese_dictionary_production
  pool: 5
  username: root
  password: 
