development:
  adapter: mysql
  encoding: utf8
  database: japanese_dictionary_development
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql
  encoding: utf8
  database: japanese_dictionary_test
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql
  encoding: utf8
  database: japanese_dictionary_production
  pool: 5
  username: root
  password: 
  socket: /var/run/mysqld/mysqld.sock
